frr version 8.4_git
frr defaults traditional
hostname p3
no ipv6 forwarding
!
interface eth1
 ip address 10.0.3.2/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 10.0.6.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
exit
!
interface lo
 ip address 10.255.255.4/32
 ip ospf area 0.0.0.0
 ip ospf passive
exit
!
router bgp 65000
 bgp router-id 10.255.255.4
 no bgp ebgp-requires-policy
 neighbor 10.255.255.5 remote-as 65000
 neighbor 10.255.255.5 update-source lo
 neighbor 10.255.255.6 remote-as 65000
 neighbor 10.255.255.6 update-source lo
 !
 address-family ipv4 unicast
  network 10.255.255.4/32
  neighbor 10.255.255.6 next-hop-self
 exit-address-family
exit
!
router ospf
 ospf router-id 10.255.255.4
exit
!
